### ISSUE TITLE
Weight shape mismatch

### ISSUE THREAD

**Issue by lyuxinghe** [KangLiao929/OrdinalDistortion#4]
Hi! Thanks for the great work! 

While trying to run inference using test.py in the default setting with weights downloaded, the code throws the following error:

Traceback (most recent call last):
  File "/root/VR2S/preprocess/OrdinalDistortion/test.py", line 59, in <module>
    test(opt)
  File "/root/VR2S/preprocess/OrdinalDistortion/test.py", line 21, in test
    model.load_weights(opt.save_weights_path, by_name=True)
  File "/root/miniconda3/envs/dev/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/miniconda3/envs/dev/lib/python3.9/site-packages/keras/saving/hdf5_format.py", line 944, in load_weights_from_hdf5_group_by_name
    raise ValueError(
ValueError: Shape mismatch in layer #_4 (named conv2d_6) for weight conv2d_6/kernel:0. Weight expects shape (3, 3, 64, 256). Received saved weight with shape (64, 4, 1, 1)

**Comment by KangLiao929** [comment]
> Hi! Thanks for the great work!
> 
> While trying to run inference using test.py in the default setting with weights downloaded, the code throws the following error:
> 
> Traceback (most recent call last): File "/root/VR2S/preprocess/OrdinalDistortion/test.py", line 59, in test(opt) File "/root/VR2S/preprocess/OrdinalDistortion/test.py", line 21, in test model.load_weights(opt.save_weights_path, by_name=True) File "/root/miniconda3/envs/dev/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler raise e.with_traceback(filtered_tb) from None File "/root/miniconda3/envs/dev/lib/python3.9/site-packages/keras/saving/hdf5_format.py", line 944, in load_weights_from_hdf5_group_by_name raise ValueError( ValueError: Shape mismatch in layer #_4 (named conv2d_6) for weight conv2d_6/kernel:0. Weight expects shape (3, 3, 64, 256). Received saved weight with shape (64, 4, 1, 1)

Hi, you may try to change the loading way from ```model.load_weights(weights_path, by_name=True)``` to ```model.load_weights(weights_path)```. It depends on the different versions of the framework.
